# Site settings
title: 
description: Molly Offer-Westort
baseurl: ""
url: "http://mollyow.github.io"
author:
  name: Molly Offer-Westort
  email: mollyow@gmail.com

gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
